<?php

namespace Drupal\gercekedebiyat\Form;

use Drupal\Core\File\FileSystem;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;

class AuthorsFromCsv extends FormBase {

  /**
   * @return string|void
   */
  public function getFormId() {
    return 'gercekedebiyat.upload';
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @return array
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['csv'] = [
      '#type' => 'managed_file',
      '#title' => 'Yazarları barındıran CSV dosyasını yükleyin.',
      '#upload_validators' => [
        'file_validate_extensions' => ['csv'],
      ],
      '#upload_location' => 'public://',
    ];
    $form['submit'] = [
      '#type' => 'submit',
      '#value' => 'Yükle',
    ];
    return $form;
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $fid = $form_state->getValue('csv');
    dpm($fid);
    $input = File::load(reset($fid));
    $input->setPermanent();
    $uri = \Drupal::service('file_system')->realpath($input->getFileUri());
    dpm($uri);
    $file = fopen($uri, "r");
    while (!feof($file)) {
      $content = fgetcsv($file);
      $node = Node::create([
        'type' => 'yazi',
        'title' => $content[4],
      ]);
      $node->save();
    }
  }

}